/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.pathmazing.projectcontact.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import java.util.Date;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the ProjectContact service. Represents a row in the &quot;Pathmazing_ProjectContact&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.pathmazing.projectcontact.model.impl.ProjectContactModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.pathmazing.projectcontact.model.impl.ProjectContactImpl</code>.
 * </p>
 *
 * @author Brian Wing Shun Chan
 * @see ProjectContact
 * @generated
 */
@ProviderType
public interface ProjectContactModel extends BaseModel<ProjectContact> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a project contact model instance should use the {@link ProjectContact} interface instead.
	 */

	/**
	 * Returns the primary key of this project contact.
	 *
	 * @return the primary key of this project contact
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this project contact.
	 *
	 * @param primaryKey the primary key of this project contact
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this project contact.
	 *
	 * @return the uuid of this project contact
	 */
	@AutoEscape
	public String getUuid();

	/**
	 * Sets the uuid of this project contact.
	 *
	 * @param uuid the uuid of this project contact
	 */
	public void setUuid(String uuid);

	/**
	 * Returns the project contact ID of this project contact.
	 *
	 * @return the project contact ID of this project contact
	 */
	public long getProjectContactId();

	/**
	 * Sets the project contact ID of this project contact.
	 *
	 * @param projectContactId the project contact ID of this project contact
	 */
	public void setProjectContactId(long projectContactId);

	/**
	 * Returns the create date of this project contact.
	 *
	 * @return the create date of this project contact
	 */
	public Date getCreateDate();

	/**
	 * Sets the create date of this project contact.
	 *
	 * @param createDate the create date of this project contact
	 */
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this project contact.
	 *
	 * @return the modified date of this project contact
	 */
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this project contact.
	 *
	 * @param modifiedDate the modified date of this project contact
	 */
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the client name of this project contact.
	 *
	 * @return the client name of this project contact
	 */
	@AutoEscape
	public String getClientName();

	/**
	 * Sets the client name of this project contact.
	 *
	 * @param clientName the client name of this project contact
	 */
	public void setClientName(String clientName);

	/**
	 * Returns the email of this project contact.
	 *
	 * @return the email of this project contact
	 */
	@AutoEscape
	public String getEmail();

	/**
	 * Sets the email of this project contact.
	 *
	 * @param email the email of this project contact
	 */
	public void setEmail(String email);

	/**
	 * Returns the client company of this project contact.
	 *
	 * @return the client company of this project contact
	 */
	@AutoEscape
	public String getClientCompany();

	/**
	 * Sets the client company of this project contact.
	 *
	 * @param clientCompany the client company of this project contact
	 */
	public void setClientCompany(String clientCompany);

	/**
	 * Returns the description of this project contact.
	 *
	 * @return the description of this project contact
	 */
	@AutoEscape
	public String getDescription();

	/**
	 * Sets the description of this project contact.
	 *
	 * @param description the description of this project contact
	 */
	public void setDescription(String description);

	/**
	 * Returns the cooperate by of this project contact.
	 *
	 * @return the cooperate by of this project contact
	 */
	@AutoEscape
	public String getCooperateBy();

	/**
	 * Sets the cooperate by of this project contact.
	 *
	 * @param cooperateBy the cooperate by of this project contact
	 */
	public void setCooperateBy(String cooperateBy);

}